//Home actions
export const GET_CAR_OF_THE_WEEK_REQUEST = 'GET_CAR_OF_THE_WEEK_REQUEST'
export const GET_CAR_OF_THE_WEEK_SUCCESS = 'GET_CAR_OF_THE_WEEK_SUCCESS'

//Search Actions
export const GET_MAKES_REQUEST = 'GET_MAKES_REQUEST'
export const GET_MAKES_REQUEST_SUCCESS = 'GET_MAKES_REQUEST_SUCCESS'
export const GET_MODELS_REQUEST =  'GET_MODELS_REQUEST'
export const GET_MODELS_REQUEST_SUCCESS = 'GET_MODELS_REQUEST_SUCCESS'
export const ON_SEARCH_LOAD = 'ON_SEARCH_LOAD'

//Select Box Actions
export const SET_MAKE = 'SET_MAKE'
export const SET_MODEL = 'SET_MODEL'
export const NAVIGATE_TO_DETAILS = 'NAVIGATE_TO_DETAILS'

//Details Actions
export const ON_DETAILS_LOAD = 'ON_DETAILS_LOAD'
